name: Daily Crypto Jobs Scraping and Inference

on:
  schedule:
    # Run at 6 PM EST (22:00 UTC, as EST is UTC-5 without daylight saving)
    - cron: '0 22 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-infer-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Display ChromeDriver and Chrome versions
        run: |
          chromedriver --version
          google-chrome --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Make sure webdriver-manager is installed
          pip install webdriver-manager
      
      - name: Set up environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      
      - name: Run job ingest pipeline
        run: python ingest.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update job listings [skip ci]" && git push) 